### ISSUE TITLE
Support for private_key_path in connection string

### ISSUE THREAD

**Issue by sfc-gh-arath** [Snowflake-Labs/snowflake-cli#101]
Snowsql supports https://docs.snowflake.com/en/user-guide/snowsql-start#using-key-pair-authentication-key-pair-rotation

**Comment by sfc-gh-tfriebel** [comment]
My customer requires Key Pair Authentication as well, as their CyberSec rules forbid using username/password. Any timeline when this will be available you can share.

**Comment by adionisio8** [comment]
Any idea when this feature would be added?

**Comment by sfc-gh-turbaszek** [comment]
Already supported thanks to #607
