### ISSUE TITLE
SNOW-927596: Add Handling for the new External Access Integrations

### ISSUE THREAD

**Issue by jacksond80** [Snowflake-Labs/snowflake-cli#425]
### Description

Snowflake introduced external access integrations, and for functions and procedures there is now a new property; EXTERNAL_ACCESS_INTEGRATIONS.

Would be great to add this property to the `snow snowpark procedure/function create` command.

### Context

As a workaround, we currently deploy the procedure/function as is and then execute an alter statement using `snow sql --query` to add external access integrations to a function or procedure.

This should all be handled with the `snow snowpark procedure/function create` command.

**Comment by sfc-gh-turbaszek** [comment]
Done in #560
