### ISSUE TITLE
SNOW-988153: Please consider the option to drop or remove a SPCS service

### ISSUE THREAD

**Issue by sfc-gh-yostrinsky** [Snowflake-Labs/snowflake-cli#596]
### Description

When trying to deploy a service with a name that already exists it fails.
1. Can we add a `snow container service drop` to remove a service?
2. Can we add a `snow container service deploy` to drop and create a service?

Thanks!

**Comment by sfc-gh-yostrinsky** [comment]
Thanks, still having it in the "snow container service" area makes more sense I believe.

**Comment by sfc-gh-turbaszek** [comment]
Closing because of `snow object drop` approach
