### ISSUE TITLE
SNOW-988515: Please have a command to simply return a repository URL

### ISSUE THREAD

**Issue by sfc-gh-yostrinsky** [Snowflake-Labs/snowflake-cli#597]
### Description

Hi.
A common operation could be to create (or fetch) an image repo, take the URL to build and tag an image, and push it to the URL.
So getting the URL easily could make the process clearer. This is the process today:
```shell
repo_url=$(snow sql -c <connection name> --schema <repo schema> -q "SHOW IMAGE REPOSITORIES;" --format=JSON | jq -r ".[] | .repository_url")

snow registry token -c <connection name> --format JSON| docker login $repo_url -u sessiontoken0 --password-stdin

docker build --platform linux/amd64 -t $repo_url/<image>:<tag> .

docker push $repo_url/<image>:<tag>
```

Not even sure how this will work if I have a few repos in the same schema, maybe include a repo name parameter?
Thanks!

**Comment by sfc-gh-turbaszek** [comment]
Done in #708
