### ISSUE TITLE
SNOW-999003: Nativeapp: unify print with log.info

### ISSUE THREAD

**Issue by sfc-gh-pczajka** [Snowflake-Labs/snowflake-cli#631]
### Description

nativeapp uses "print" to show user current execution status, while the rest of the snowcli use "log.info"
After introducing file logging (SNOW-986254) log messages are concurrently saved to a file.

To be discussed: current default console output level is set to "ERROR" ("INFO" for --verbose)

**Comment by sfc-gh-turbaszek** [comment]
Closing thanks to #659
