### ISSUE TITLE
SNOW-1060471: `snow connection add` with password prints the warning twice

### ISSUE THREAD

**Issue by sfc-gh-davwang** [Snowflake-Labs/snowflake-cli#791]
### SnowCLI version

 2.0.1rc0

### Python version

3.11.7

### Platform

macOS-14.3-arm64-arm-64bit

### What happened

**Update 2/16/24**: Actually this seems like a bug from Typer. See this [question](https://github.com/tiangolo/typer/discussions/700). 

A workaround could be to validate the password at the beginning of the function rather than as an input callback. In other words, if password is not None, then that means the password was passed either through prompt or command line option, in which case we display the appropriate warning. This would change the time when we display the warning from right after you input a password in the prompt to after all inputs have been entered.

**Another question is: If we offer the prompt option for password, do we want to display the warning? I know that if we pass in the password with the `--password` flag it is insecure because it can end up in shell logs but is that true if the user passes in their password with prompt?** 

**Previous Comment 2/16/24**

When you run or `snow connection add` and fill in the password with the prompt, a warning is printed saying `WARNING! Using --password via the CLI is insecure. Use environment variables instead.` However, this warning is printed twice which is not intended. Note that the warning correctly prints once if you pass the password with the command line option (e.g. `snow connection add ... --password pass`). 

<img width="696" alt="image" src="https://github.com/Snowflake-Labs/snowflake-cli/assets/156019931/203ab388-521c-4f4c-86fe-9940218fea79">

It seems that when you pass in input via prompt instead of CLI option, it actually applies the callback to that input twice. I quickly spun up another example where the callback actually modifies the input and the input is modified twice.

<img width="620" alt="image" src="https://github.com/Snowflake-Labs/snowflake-cli/assets/156019931/e12328e5-0b8c-43bf-b956-cd8aa3c084e1">
<img width="481" alt="image" src="https://github.com/Snowflake-Labs/snowflake-cli/assets/156019931/6ac8cb5c-0915-4bae-bd6e-92c7077b9288">

### Console output

```Shell
(snowflake-cli-labs) (main) snowcli$ snow connection add
Name for this connection: test
Snowflake account name: test
Snowflake username: test
Snowflake password [optional]: 
WARNING! Using --password via the CLI is insecure. Use environment variables instead.
WARNING! Using --password via the CLI is insecure. Use environment variables instead.
```

### How to reproduce

Run `snow connection add` without any arguments, fill in connection details including the password. It should show two warnings pop up.

**Comment by sfc-gh-jsikorski** [comment]
Hi, thanks for reporting this. 
It seems, that it is a typer issue, but i will look if we can avoid it in any way
https://github.com/tiangolo/typer/discussions/700
