### ISSUE TITLE
SNOW-1062717: Getting Intel warnings and bad owner/permissions while using snow cli

### ISSUE THREAD

**Issue by sfc-gh-puneet-lakhanpal** [Snowflake-Labs/snowflake-cli#803]
### SnowCLI version

SnowCLI Version: 2.0.0rc1

### Python version

Python 3.10.13

### Platform

macOS-10.16-x86_64-i386-64bit

### What happened

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
/Users/plakhanpal/anaconda3/envs/spcsintro/lib/python3.10/site-packages/snowflake/connector/config_manager.py:344: UserWarning: Bad owner or permissions on /Users/plakhanpal/Library/Application Support/snowflake/config.toml.
 * To change owner, run `chown $USER "/Users/plakhanpal/Library/Application Support/snowflake/config.toml"`.
 * To restrict permissions, run `chmod 0600 "/Users/plakhanpal/Library/Application Support/snowflake/config.toml"`.

  warn(f"Bad owner or permissions on {str(filep)}{chmod_message}")

### Console output

```Shell
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
/Users/plakhanpal/anaconda3/envs/spcsintro/lib/python3.10/site-packages/snowflake/connector/config_manager.py:344: UserWarning: Bad owner or permissions on /Users/plakhanpal/Library/Application Support/snowflake/config.toml.
 * To change owner, run `chown $USER "/Users/plakhanpal/Library/Application Support/snowflake/config.toml"`.
 * To restrict permissions, run `chmod 0600 "/Users/plakhanpal/Library/Application Support/snowflake/config.toml"`.

  warn(f"Bad owner or permissions on {str(filep)}{chmod_message}")
```

### How to reproduce

conda-env.yml:

name: spcsintro
channels:
  - https://repo.anaconda.com/pkgs/snowflake
dependencies:
  - python=3.10
  - snowflake-snowpark-python[pandas]
  - ipykernel
  - tensorflow
  - tensorboard
  - pip
  - pip:
    - snowflake-cli-labs==2.0.0rc1
    - jax>=0.3.15
    - libclang>=13.0.0
    - tensorflow-io-gcs-filesystem>=0.23.1

commands:
CONDA_SUBDIR=osx-64 conda env create --file conda_env.yml
conda activate spcsintro
conda config --env --set subdir osx-64
snow connection add

**Comment by sfc-gh-astus** [comment]
Hi. Intel error is not related with SnowCLI, check this issue https://github.com/ContinuumIO/anaconda-issues/issues/13236 .

To increase security SnowCLI allow only to use default config with restrict permissions. Please run `chmod 0600 "/Users/plakhanpal/Library/Application Support/snowflake/config.toml"`
